---
name: HiddenInfo
author: ArceusMatt
authors: ArceusMatt, kpwn_
descrption: Plugin that shows players hidden info.
version: 1.0.1indev
api: [2.0.0]
main: HiddenInfo\Main

commands:
    hiddeninfo:
        description: HiddenInfo Main Command.
        permission: hiddeninf.cmd
permissions:
    hiddeninf.cmd:
        default: op
---